name: patchioner
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openjdk=8.0.152
  - openssl=3.0.15
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - asttokens==3.0.0
      - attrs==24.2.0
      - backcall==0.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - git+https://github.com/openai/CLIP.git
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.9
      - decorator==5.1.1
      - dill==0.3.9
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fonttools==4.55.2
      - fsspec==2024.10.0
      - ftfy==6.2.0
      - h5py==3.11.0
      - huggingface-hub==0.26.3
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multiprocess==0.70.17
      - munkres==1.1.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - open-clip-torch==2.30.0
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.4
      - pathos==0.3.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pox==0.3.5
      - ppft==1.7.6.9
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.7
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rpds-py==0.20.1
      - safetensors==0.4.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - six==1.17.0
      - speaksee==0.0.1
      - stack-data==0.6.3
      - sympy==1.13.3
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - timm==1.0.12
      - tokenizers==0.20.3
      - torch==2.4.1
      - torchvision==0.19.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.3
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - zipp==3.20.2
      - sentence-transformers==3.2.1
      - nltk==3.9.1
