decap_weights: '/raid/datasets/models_weights/decap_weights/clip-b32-ksplits/coco_karpathy-009.pt'
prefix_size: 512 
support_memory_size: 0
dino_model: 'vit_base_patch32_clip_224.openai'
normalize: False
resize_dim: 224
crop_dim: 224
clip_model_name: 'ViT-B/32'
use_talk2dino_project: False

# nested config
viecap:
  project_length: 10
  temperature: 0.01
  top_k: 3
  threshold: 0.4
  language_model: 'gpt2'
  name_of_entities_text: coco_entities #vinvl_vgoi_entities
  files_path: '/raid/datasets/viecap_files/'
  prompt_ensemble: True
  weight_path: '/raid/datasets/viecap_files/checkpoints/train_coco/coco_prefix-0014.pt'
  using_hard_prompt: True
  soft_prompt_first: True
  only_hard_prompt: False
  using_greedy_search: True #if false, use beam search
  beam_width: 5
  text_prompt: None

